### ISSUE TITLE
Overheating on laptop Matebook 13

### ISSUE THREAD

**Issue by alexmcgil** [lutris/docs#58]
Hi, after installation drivers on Huawei Matebook 13 2020 [Intel] with NVIDIA MX250, (Elemetary os) my notebook overheating and very fast discharge (1h vs 8h). Any ideas how to fix it? So, with installed drivers, i try to play in a "Katana: ZERO" with Proton and saw only white screen. (Maybe it's problems with game or my system)

**Comment by HelenB13** [comment]
I had the same issue with my HP laptop. It turned out that it's simply a hotter CPU by nature and the slimmer 15" chassis paired with HP sub-ideal cooling solution lead to undesired overheating. I needed to solve the issue fast as I had to finish one urgent project. The problem was Bad thermal paste as per my googling. You can decrease the temps by using "ThrottleStop" software (Google some videos about it). Also, here some other suggestions. Make sure the system is completely up to date first. Manually run windows updates. Then make sure the bios is up to date. Clean the vents and inspect the fans.

**Comment by alexmcgil** [comment]
> I had the same issue with my HP laptop. It turned out that it's simply a hotter CPU by nature and the slimmer 15" chassis paired with HP sub-ideal cooling solution lead to undesired overheating. I needed to solve the issue fast as I had to finish one urgent project with the guys from https://www.topwritersreview.com/reviews/mymathgenius/. The problem was Bad thermal paste as per my googling. You can decrease the temps by using "ThrottleStop" software (Google some videos about it). Also, here some other suggestions. Make sure the system is completely up to date first. Manually run windows updates. Then make sure the bios is up to date. Clean the vents and inspect the fans.
if it was a processor problem, the matebook 13 would be heated from under windows, as well as without installed drivers, I note, for the GPU.
