### ISSUE TITLE
InstallingDrivers.md Instructions for Debian 11

### ISSUE THREAD

**Issue by ACR-Jeff** [lutris/docs#98]
The InstallingDrivers.md Doesn't provide instructions for Debian 11 installation, The InstallingDrivers.md only provides instructions for Ubuntu, Debian 11 does not work with the provided PPA's and Etc, Any help to install the drivers to Debian 11 Bullseye would be great. Thanks

**Comment by gardotd426** [comment]
@ACR-Jeff, I imagine that the idea is that anyone choosing to run Debian 11 on a gaming machine is going to know exactly what they need and how to get it. The problem is that the Lutris folks are absolutely inundated, there is way too much work to be done and there are way too few people to do it, and all of them are volunteers I believe. So when it comes to things like "which distros should we include in the InstallingDrivers documentation," they are going to make the obvious - and only sensible - choice. They're going to list the distros that comprise 90% of gamers on Linux. Debian doesn't fit in to that. 

Also, I'm not sure what you want them to do... Debian doesn't use PPAs, and there is no alternative quick and easy way to install Mesa drivers. So basically they would need to just say "On Debian, for AMD/Intel GPUs, build Mesa (both 32-bit and 64-bit) from source, follow instructions at the Mesa repository." What's the point of that? The alternative is recommending the repo Mesa packages, which are old as hell. 

Mathieu or Alex may come in behind me and say I'm completely wrong, but from everything I know, I'd say there is no real need to add Debian to InstallingDrivers.md, and that there is no way it'll happen regardless.

**Comment by ACR-Jeff** [comment]
@gardotd426 Thank you for your criticism, Not everyone that uses a Debian Distro knows everything about the distro, Learning is something that comes from many distro's. So that being said, I learned that the Debian Team has modified and compiled their own drivers which are automatically installed. Lutris doesn't see those drivers. Yet I decided to just ignore the warning, Lutris has instructions on Debian installations. This being said, They are very aware that people install on Debian machines, If Debian installation instructions are going to be provided on the Lutris website, They should provide instructions on the Driver installation as well. It only makes sense. Thanks for no help other than your criticism.
